In [1]:
# e_numpy
# pip install numpy
import numpy as np

In [2]:
arreglo_np_list = np.array( [1,2,3] )

In [3]:
arreglo_np_tupla = np.array( (1,2,3) )

In [4]:
print(type(arreglo_np_list))
print(type(arreglo_np_tupla))
print(arreglo_np_list)
print(arreglo_np_tupla)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]


In [8]:
np.ones(10000)

array([1., 1., 1., ..., 1., 1., 1.])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones( (5,2,3) )

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.ones( [2,3] ).shape

(2, 3)

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(-20, -10) # [-20, -10[

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [21]:
np.arange(30,66) # [30, 66[

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65])

In [22]:
np.arange(-20, -10 , 5)

array([-20, -15])

In [23]:
np.arange(-20, -10, 2)

array([-20, -18, -16, -14, -12])

In [24]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [25]:
np.arange(3,5,0.1).shape

(20,)

In [29]:
np.arange(3,5,0.1).reshape((5,2,2))

array([[[3. , 3.1],
        [3.2, 3.3]],

       [[3.4, 3.5],
        [3.6, 3.7]],

       [[3.8, 3.9],
        [4. , 4.1]],

       [[4.2, 4.3],
        [4.4, 4.5]],

       [[4.6, 4.7],
        [4.8, 4.9]]])

In [30]:
np.arange(3,5,0.1).reshape((5,2,2)).flatten()

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [31]:
np.arange(3,5,0.1).reshape((5,2,2)).flatten().shape

(20,)

In [135]:
np.random.randint(0, 10, 5)

array([1, 9, 8, 1, 4])

In [136]:
np.random.rand(6)

array([0.41056529, 0.05059449, 0.73913732, 0.57355416, 0.01360186,
       0.84655539])

In [137]:
a = np.array( [
    [1, 2],
    [3, 4]
] )
b = np.array( [
    [5, 6],
    [7, 8]
] )
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [138]:
# Suma 
a + b

array([[ 6,  8],
       [10, 12]])

In [139]:
# Resta 
a - b

array([[-4, -4],
       [-4, -4]])

In [140]:
# Multiplicacion
a * b

array([[ 5, 12],
       [21, 32]])

In [141]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [142]:
a ** 3

array([[ 1,  8],
       [27, 64]])

In [143]:
a % 2

array([[1, 0],
       [1, 0]])

In [144]:
a + 10

array([[11, 12],
       [13, 14]])

In [146]:
(a * 2) / 5 * 100

array([[ 40.,  80.],
       [120., 160.]])

In [147]:
a < b

array([[ True,  True],
       [ True,  True]])

In [155]:
a

array([[ 6,  8],
       [10, 12]])

In [151]:
a[a < 4]

array([1, 2, 3])

In [ ]:
a[a >= 4]

In [152]:
a += 2

In [154]:
a *= 2

In [156]:
arreglo = np.arange(1,11)

In [160]:
arreglo.sum()
arreglo.min()
arreglo.max()

10

In [162]:
matriz = np.arange(12).reshape(3,4)

In [163]:
matriz

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [165]:
matriz.sum(axis = 0)

array([12, 15, 18, 21])

In [166]:
matriz.sum(axis = 1)

array([ 6, 22, 38])

In [172]:
notas = np.array([1,2,3,5,3,2,7,8,5,3,2,9,7,6])

In [169]:
notas.mean()

4.5

In [171]:
np.median(notas)

4.0

In [173]:
np.std(notas)

2.471263413143742

In [174]:
np.var(notas)

6.107142857142857

In [175]:
path = "./05_salarios.csv"
salarios = np.genfromtxt(path, delimiter= ',')

In [176]:
salarios

array([1., 2., 4., 6., 4., 3., 2., 1., 5., 6., 7., 9., 9., 7., 5., 4., 5.,
       4., 2., 1., 5., 6., 7., 9., 0., 7., 6., 4., 3., 2., 1., 5.])

In [177]:
salarios.mean()

4.4375

In [178]:
once = np.arange(11)**2

In [179]:
once

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [180]:
once[::2]

array([  0,   4,  16,  36,  64, 100])

In [181]:
once[::3]

array([ 0,  9, 36, 81])

In [182]:
once[::5]

array([  0,  25, 100])

In [183]:
arreglo_split = np.arange(15)
np.split(arreglo_split, 3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [184]:
np.split(arreglo_split, [2,6,9,13])

[array([0, 1]),
 array([2, 3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14])]

In [185]:
salarios

array([1., 2., 4., 6., 4., 3., 2., 1., 5., 6., 7., 9., 9., 7., 5., 4., 5.,
       4., 2., 1., 5., 6., 7., 9., 0., 7., 6., 4., 3., 2., 1., 5.])

In [186]:
print(salarios.sort())
print(salarios)

None
[0. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 4. 4. 4. 4. 4. 5. 5. 5. 5. 5. 6. 6. 6.
 6. 7. 7. 7. 7. 9. 9. 9.]


In [187]:
salarios[::-1].sort()
print(salarios)

[9. 9. 9. 7. 7. 7. 7. 6. 6. 6. 6. 5. 5. 5. 5. 5. 4. 4. 4. 4. 4. 3. 3. 2.
 2. 2. 2. 1. 1. 1. 1. 0.]
